### ISSUE TITLE
Java version compatibility

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#31]
This library should take Java version compatibility between 6 & 7 JDK and 8 JDK into account due to `XmlInputFormat`.

I think it would be better to change it into Scala.

**Comment by JoshRosen** [comment]
How is the choice of language (Java vs. Scala) related to JVM compatibility? These seem like orthogonal issues tom e.

**Comment by HyukjinKwon** [comment]
Ah, I think I should correct the issue name and contents.

I just wanted to say that we might have to remove the Java code in order to not care of Java version stuff.

I complied this library compiled in Java 8 and I found I could not execute with Java 7 with the message below.

```
java.lang.UnsupportedClassVersionError: com/databricks/hadoop/mapreduce/lib/input/XmlInputFormat :
 Unsupported major.minor version 52.0
```

**Comment by JoshRosen** [comment]
The presence of Java source code isn't the cause of that compatibility problem; rather, the issue is that the Java 8 compiler, by default, emits Java-8-compatible bytecode and needs to be explicitly instructed to generate bytecode which is compatible with Java 7. See https://github.com/databricks/spark-redshift/pull/113 for an example of how to configure `scalac` and `javac` to target specific JVM / JDK versions.

**Comment by HyukjinKwon** [comment]
Thank you very much for your great explanation!

**Comment by HyukjinKwon** [comment]
I will close this issue but leave the PR anyway because anyway I think it would be better to change Java code into Scala for now.
