### ISSUE TITLE
Release 0.5.0 of spark-xml

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#361]
Need a new release. There are many good fixes were done.

**Comment by HyukjinKwon** [comment]
@srowen, do you have some more changes to push? If so, I can wait for another week. If you think it's mostly done, I will make a release tomorrow.

**Comment by srowen** [comment]
I'd like to run down one more potential issue -- following up on https://github.com/databricks/spark-xml/pull/358 In the course of that I noticed some loops have a condition like `shouldStop = shouldStop && parser.hasNext`. Because the flag is always false when the loop starts, this is basically doing nothing. I 'fixed' it but it causes a few tests to fail that relate to corrupt records. So maybe I should investigate for a day or two to see if we need to fix one more thing there.

**Comment by HyukjinKwon** [comment]
Yea .  Makes sense. Let me take a look tomorrow.

**Comment by HyukjinKwon** [comment]
I pushed

1. Released
2. made a tag v0.5.0
3. made a branch branch-0.5

I'm going to make a release note by the end of today (https://github.com/databricks/spark-xml/releases/tag/v0.5.0)

**Comment by HyukjinKwon** [comment]
Release is done! and note is also done! https://github.com/databricks/spark-xml/releases/tag/v0.5.0
