### ISSUE TITLE
Returned as StringType instead of StructType if any element contains whitespaces

### ISSUE THREAD

**Issue by hwh7** [databricks/spark-xml#396]
Hello, I am developing something using pyspark and com.databricks:spark-xml_2.11:0.4.1.

When parsing a xml which contains whitespaces inside a element, the result returns as StringType instead of StructType.

For example. I extract data like this:
Select a.b from [TABLE_NAME]

Data 1.
`<a><b><c>xx</c><b><b><c>yy</c><b></a>`
This returns as StructType.

Data 2. If any element in the list has whitespaces like this:
`<a><b><c>xx</c><b><b>  <b></a>`
This returns as StringType.

Is it a desired result?

**Comment by srowen** [comment]
In your example you mean to close the `<b>` tags not open new ones right?

The problem here is that the XML doesn't have a consistent schema. Sometimes `<b>` is a struct with child field `c`, and sometimes it's a string. Inferring `StringType` makes sense in this way.

What it won't do right now is assume that `b` just has an _optional_ child `c`. I think that if you infer the schema, then modify the schema to specify the type of `b` manually as a `StructType` with child `c`, then parse again with that modified schema, it would work.

**Comment by samsung-hwh7** [comment]
Oh. I am very sorry for bad mistake.

Data 1.
<a><b><c>xx</c></b><b><c>yy</c></b></a>
This returns as StructType.

Data 2. If any element in the list has whitespaces like this:
<a><b><c>xx</c></b><b> </b></a>
This returns as StringType.

What I meant was this.

**Comment by srowen** [comment]
Yes I got it, but the answer is the same. Try modifying the schema.
