### ISSUE TITLE
Should consider extending from Datasource V2

### ISSUE THREAD

**Issue by rxin** [databricks/spark-xml#4]
So that the XML data source gains both write support and partitioning support.

Link from https://github.com/HyukjinKwon/spark-xml/issues/6

**Comment by HyukjinKwon** [comment]
I am leaving this link for a reminder that `HadoopFsRelation` is updated.
https://issues.apache.org/jira/browse/SPARK-13664

**Comment by HyukjinKwon** [comment]
@rxin, I update this to Data source v2 but please revert my change if I'm mistaken.

**Comment by devendrasr** [comment]
Is there any work going on around this?

**Comment by srowen** [comment]
No work on this. Anyone who knows DSv2 well enough is welcome to try

**Comment by syedhassaanahmed** [comment]
Any progress on this issue? We'd like to use Structured Streaming as mentioned in #290

**Comment by srowen** [comment]
Same answer. WSYIWYG. Nobody is working on it.

**Comment by ericsun95** [comment]
The datasource v2 version changed a lot even between 2.4.7 and 3.0.1. I can have a try while it may change a lot for the current code base. Anyone interested too? I guess I can start with 2.4.x style first?

**Comment by srowen** [comment]
I think it's entirely fine to only support Spark 3.x in any effort here.

**Comment by ericsun95** [comment]
> I think it's entirely fine to only support Spark 3.x in any effort here.

Sure. I will fork this and try come up with a rough plan there? Or if you think it's easier to track here. I can create new relevant tickets here.

In short, I think we can follow the pattern here https://github.com/apache/spark/tree/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2 to extend latest datasource v2.

**Comment by ericsun95** [comment]
The latest pattern has the [failbackformat](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/parquet/ParquetDataSourceV2.scala#L28) so it won't affect current v1.

**Comment by srowen** [comment]
Just open a pull request here from your fork/branch, yes.

**Comment by ericsun95** [comment]
Have a look into the details of the Datasource v2 structure, there are some parts need more from current code base. I will try to follow the pattern for v2 like:
- XMLDataSourceV2
- XMLPartitionReaderFactory
- XMLScan
- XMLScanBuilder
- XMLTable
- XMLWriteBuilder

However, by following that we first need to refractor some parts by following the pattern [here](https://github.com/apache/spark/tree/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources). Similar to the text/parquet/json style, we have to have:
- `XMLFileFormat` which `extends FileFormat with DataSourceRegister` so that the `XMLDataSourceV2` could failback through failbackformat.
- `XMLDataSource` or `XMLUtils` to inferSchema with `files: Seq[FileStatus]` as input and `Option[StructType]` as output. While the current `object InferSchema` takes `RDD[String]` as an input. This might be relevant to #496.
- The `XMLPartitionReaderFactory` needs to override the buildReader function in the following style:
`buildReader(partitionedFile: PartitionedFile): PartitionReader[InternalRow]`. We will update the RDD[Row] to `Iterator[InternalRow]` in parser.
- `XMLScan` is doing something similar to the `XmlInputFormat` to split the file and it will call the `XMLPartitionReaderFactory`. 
- `XMLScanBuilder` build the XMLScan with `SupportsPushDownFilters`. This includes something from `XmlReader` I guess.
- `XMLTable` is simple as it was used to create the `ScanBuilder`. But we need specify the `supportsDataType`. I guess there exist somewhere in our code base already?
- `XMLWriteBuilder` is similar to `StaxXmlGenerator` I guess. It needs to `override def prepareWrite(
   sqlConf: SQLConf,
   job: Job, options: Map[String, String],
   dataSchema: StructType): OutputWriterFactory`. Which needs some efforts to convert.

The general follow would be `XMLDataSourceV2` (source register)-> `XMLTable` (create table) -> `XMLScanBuilder` (support push down filter) -> `XMLScan` (Partition/Split the file) -> `XMLPartitionReaderFactory` (per partition per reader)  -> `XMLPartitionReaderFactory` (support writing).

Hope to have more introductions to existing code base before going too far.

**Comment by JCZuurmond** [comment]
@ericsun95, great that you are/have been working on this! How is the progress going?

**Comment by ericsun95** [comment]
> @ericsun95, great that you are/have been working on this! How is the progress going?

Hey, I am still waiting for more people discussing this with me. As it's kind like refracting all existing code to use the new structure and the DataSourceV2 API is still unstable today. I think a minimal design is needed here and once this migration done, it's also possible to include the whole repo into the spark mainline.

**Comment by JCZuurmond** [comment]
Ok, I am not the person who can help here. Though, looking forward to some features DataSourceV2 enables

**Comment by ericsun95** [comment]
I got some time to take a look on `DataSourceV2` now. And there is a good example for this migration (https://github.com/crealytics/spark-excel/commit/4c225455d6d267682bcbaa502c5f4dfbf56b5b40).

However, before that I found lots of duplicated logic in this repo with Spark repo. For example, `ParseMode`, `PermissiveMode`, `CompressionCodecs` etc.

I am trying to clean them up first while it failed at binary incompatible [comparison](https://github.com/ericsun95/spark-xml/compare/databricks:spark-xml:master...master), which I don't think it would have huge impacts on customers as it always used with Spark dependencies, @srowen thoughts?

Another challenging part is lack of clear design pattern here due to some historical reasons, something like dependency injection could make it easier to evolve in future (I found similar issues even in Spark main repo..)

I create a branch [here](https://github.com/databricks/spark-xml/compare/master...ericsun95:spark-xml:datasourcev2) for initial structure setup on datasourceV2. Welcome discussion on it.

**Comment by srowen** [comment]
Great! yes the implementation here was copy-pasted from the JSON data source, I believe. 
I think it's OK to break binary compatibility for this reason, if we must. If there is any way to deprecate and keep existing APIs or constants without keeping the old impl, that's nicer of course.

Yes the code isn't _terrible_ but not super well designed, esp after years of tweaking and hacks to fix bugs. I'd advise not trying to redesign unless you really want to. Keep it simple at first, etc. Open a PR when ready.

**Comment by ericsun95** [comment]
Checked the history of this repo, databricks-csv and spark-csv. due to the reason that the `DataSourceV2` right now is still coupled with `DataSourceV1` closely. Refactoring seems unavoidable.

However, good things are that we still have all the commit history:

- [[SPARK-13665](https://issues.apache.org/jira/browse/SPARK-13665)][SQL] Separate the concerns of HadoopFsRelation
- [[SPARK-15543](https://issues.apache.org/jira/browse/SPARK-15543)][SQL] Rename DefaultSources to make them more self-descr…
- [SPARK-27085][SQL] Migrate CSV to File Data Source V2 

etc.

We first need to refract the `XMLRelation`, `DefaultDataSource`, etc to `DataSourceV1`, then we can onboard it to `DataSourceV2`.

**Comment by ericsun95** [comment]
@srowen  I am refactoring the `StaxXmlGenerator` to similar like `org.apache.spark.sql.catalyst.csv.UnivocityGenerator` and create a `XmlOutputWriter` to be similar like the `org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter` so that the [`org.apache.spark.sql.execution.datasources.FileFormatWriter`](https://github.com/apache/spark/blob/55ee406df9933ca522bc98c2d2ccc0245e97ff67/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala) could take advantage of it.

However, the logic [here](https://github.com/apache/spark/blob/55ee406df9933ca522bc98c2d2ccc0245e97ff67/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala#L313-L327) is kind of different from the logic in `XmlFile` where we have fine grained checks on each partition and write differently on `firstRow` and `lastRow`. 

I am not so sure if we need a feature request on Spark to expose the partition info to outputWriter? Right now they deal with all the internal row as the same row and hide all the logics in `FileFormatWriter`.

**Comment by ericsun95** [comment]
> @srowen  I am refactoring the `StaxXmlGenerator` to similar like `org.apache.spark.sql.catalyst.csv.UnivocityGenerator` and create a `XmlOutputWriter` to be similar like the `org.apache.spark.sql.execution.datasources.csv.CsvOutputWriter` so that the [`org.apache.spark.sql.execution.datasources.FileFormatWriter`](https://github.com/apache/spark/blob/55ee406df9933ca522bc98c2d2ccc0245e97ff67/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala) could take advantage of it.
> 
> 
> 
> However, the logic [here](https://github.com/apache/spark/blob/55ee406df9933ca522bc98c2d2ccc0245e97ff67/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala#L313-L327) is kind of different from the logic in `XmlFile` where we have fine grained checks on each partition and write differently on `firstRow` and `lastRow`. 
> 
> 
> 
> I am not so sure if we need a feature request on Spark to expose the partition info to outputWriter? Right now they deal with all the internal row as the same row and hide all the logics in `FileFormatWriter`.


Never mind, it seems there is a way to achieve this in the generator with a car variable

**Comment by ericsun95** [comment]
Just get one afternoon to continue look into it, One challenging part is that:
```  
def withCharset(
      context: SparkContext,
      location: String,
      charset: String,
      rowTag: String): RDD[String] = {
    // This just checks the charset's validity early, to keep behavior
    Charset.forName(charset)
    val config = new Configuration(context.hadoopConfiguration)
    config.set(XmlInputFormat.START_TAG_KEY, s"<$rowTag>")
    config.set(XmlInputFormat.END_TAG_KEY, s"</$rowTag>")
    config.set(XmlInputFormat.ENCODING_KEY, charset)
    context.newAPIHadoopFile(location,
      classOf[XmlInputFormat],
      classOf[LongWritable],
      classOf[Text],
      config).map { case (_, text) => text.toString }
  }
  ```
  The core reading logic here use the `newAPIHadoopFile` which requires the context to be initialized.
  In the new api `FileFormat`,  the reading part
  ```
    override def buildReader(sparkSession: SparkSession,
                           dataSchema: StructType,
                           partitionSchema: StructType,
                           requiredSchema: StructType,
                           filters: Seq[Filter],
                           options: Map[String, String],
                           hadoopConf: Configuration): PartitionedFile => Iterator[InternalRow] = {
```
Is actually executed in the executor side so we can't use `sparkSession.sparkContext` as it will return null here.
Anyone knows any alternative with `newAPIHadoopFile` that we can use with the new pattern?

**Comment by adriennn** [comment]
@srowen and @HyukjinKwon any help for @ericsun95 ? This seems to be holding back xml data from being useable as structured streaming source?

**Comment by srowen** [comment]
Yep, but, I can't do it and not aware of anyone working on it.

**Comment by JCZuurmond** [comment]
@srowen : Does closing this feature mean that it is implemented?

**Comment by srowen** [comment]
No, was not implemented. This repo is shutting down as the project has been merged into Spark
