### ISSUE TITLE
XML not imported properly when tag has both value and attribute

### ISSUE THREAD

**Issue by gmoore016** [databricks/spark-xml#415]
It seems as though certain tags fail to load when their siblings have text values as well as attributes. As an example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
<foo> issue <bar> lorem </bar> </foo>
<missing> ipsum </missing>
</root>
```
When I load this using `xml = sql.read.format("xml").option("rowTag", "root").option("inferSchema", "false").option("mode", "FAILFAST").load("example.xml")` then run `xml.printSchema()`, I get the following schema:
```
root
|-- bar: string (nullable = true)
|-- foo: string (nullable = true)
```
which is notably missing any reference to the `<missing>` tag from the example XML, and lists `<bar>` as a sibling of `<foo>` rather than as a child. However, I do not seem to have this problem when I remove `issue`. I double checked via [this website](https://www.w3schools.com/xml/xml_validator.asp), and the example appears to be valid XML. 
Is there any way I can access the text from `<missing>`?

**Comment by srowen** [comment]
Hm, not sure. I know there are problems handling mixed text/element children well. The problem is it's not super clear how this maps to a tabular schema: foo is a string, with child bar that's a string? that's a fine interpretation in this case. But what if foo had more text children after bar? It does fine on less-ambiguous cases where the XML is basically a straight tabular data set encoded as XML.

That said I don't see a good reason it misses 'missing' here. What happen if you infer the schema though?

**Comment by gmoore016** [comment]
When I run `xml = sql.read.format("xml").option("rowTag", "root").option("inferSchema", "true").load("example.xml")` and immediately run `xml.printSchema()` I receive the same schema as above.

To give a use case, I'm looking at text with in-text citations. For example, `<text> According to <ref> Turing (1936) </ref>, computable numbers are...</text>`. 

At least for this context, I might suggest an array containing each string. For example, given `<foo> lorem <bar> text </bar> ipsum </foo>`, you would have the `bar` element as well as the array `["lorem", "ipsum"]`. This would yield the schema:
```{xml}
root
|--foo
|    |--_values: array
|    |    |--element: string
|    |--bar: string
```
As an alternative, you may wish to simply store the full string; in the above case, you could have both the `bar` element as well as the string `"lorem <bar> text </bar> ipsum"`--though this may get quite large if the internal elements are complex. These both would make it relatively simple to construct the meaning of the original sentence while parsing the XML in a usable way.

**Comment by srowen** [comment]
What if you give it the desired schema? with foo with nested bar element, and missing as a separate field? I think it will 'work' if you tell it foo is a string, but of course that doesn't parse the bar child elements; that would have to happen separately.

**Comment by gmoore016** [comment]
I think this is what you meant--I try to give it the schema:
```python
customSchema = StructType([
    StructField("foo", StringType(), True),
    StructField("missing", StringType(), True)
])
```
This way, all of `foo` will be interpreted as a string, including the `<bar>` tags, and it should know to look for `missing`. However, when I try xml.show() I get the proper value for `foo` but `missing` appears to have a null value rather than the exepcted "ipsum", which makes me think it's still not recognizing the actual `missing` field.

**Comment by srowen** [comment]
So, one thing I'm puzzled about is why you get the schema you see above, which seems more wrong than most. (It actually always infers the _structure_ of the schema unless given one manually, but only infers types if `inferSchema` is `true`). I get the following schema following
```
StructType(StructField(foo,StructType(StructField(bar,StringType,true)),true), StructField(missing,StringType,true))
```
That's almost right:
```
+-------+-------+
|    foo|missing|
+-------+-------+
|[lorem]|  ipsum|
+-------+-------+
```
But not quite enough as "issue" is missing. I'm not sure what the difference is unless maybe this is from an older version and something along these lines was fixed? if so, then updating would at least get you this far.

Yes you get a similar result from treating `foo` as a String - XML comes back but still not the "issue" string.

A general fix might be hard just because of some difficulty mapping a bunch of text children to the schema. However the case of one extra child text element seems at least unambiguous because we generally map that to `_VALUE` where there are other children like attributes. I will try to debug further to see if there's an obvious way to infer this type of structure without a big overhaul.

**Comment by srowen** [comment]
Ack, wait, disregard this. I was looking at my wrong test file. Let me update in a bit with more correct results

**Comment by srowen** [comment]
https://github.com/databricks/spark-xml/pull/416 has some progress on this issue plus discussion. We at least have to get it to return `missing` as the current inferred schema is plainly wrong. Whether to handle the character elements is another question.

**Comment by srowen** [comment]
I believe #416 partly resolves this. It doesn't support reading the text outside the elements, but correctly parses the rest, as in `<missing>`
