### ISSUE TITLE
Row tag with only text as child isn't parsed

### ISSUE THREAD

**Issue by valadan** [databricks/spark-xml#428]
I am using Spark 2.4.3 (w/ Scala 2.11) and Spark XML version 0.6.0 (also tried 0.7.0)

I am attempting read this xml file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<x date="201912022200" type="daily">
<ylist>
<y Description1Id="1" RecordType="Person">SomeValue</y>
</ylist>
</x>
```

I am using this code to do so:

```
val test = spark.read.format("com.databricks.spark.xml")
      .option("rootTag", "ylist")
      .option("rowTag", "y")
      .load("somefile.xml")
 
test.printSchema
```

The schema that is being inferred is incorrect:
```
root
 |-- _Description1Id: long (nullable = true)
 |-- _RecordType: string (nullable = true)
```

The value tag is missing.

**Comment by srowen** [comment]
Yeah, this behavior is kind of inconsistent. The issue is that your row is `<y>` and it doesn't have named children, just a string. That's not usually supported. However if `<ylist>` is your row, you'll get the attributes as fields of `y`, but also a `_VALUE` column in `y` with that string. If you can select `<ylist>` instead as the row, you'll get it all.

I should have another look at why the behavior is different though. I'd also kind of expect you get a `_VALUE` column by default for a string child of the row tag.

**Comment by valadan** [comment]
Ok. It is not ideal but I think I can select <ylist> and then explode the array to get what I want.

I do think though that the current behavior is not what you would expect. 

Thanks!

**Comment by srowen** [comment]
I did look into this, and I don't think there's an 'easy' fix, though with some hacking it wouldn't be too hard.

So, I'm still on the fence about whether the behavior is consistent or not. Generally speaking, things without a 'name' are not parsed because in a table structure, columns need names. So `<row>foo</row>` doesn't work. `<row><foo>bar</foo></bar>` does because it we can see a name for the string value, "foo". `<row foo="bar"/>` works too because the string value has an identifiable name. But then, what about `<row><foo bar="baz">bing</foo></row>? it's clear there's a `foo._bar` column, but it would be inconsistent to refuse to recognize "bing" as a named column because it works without attributes. It becomes `foo._VALUE` instead of the value of a column `foo`, because `foo` has to be a struct now.

It wouldn't be crazy to read `<row foo="bar">bing</row>` as having columns `foo` and `_VALUE`. But the value "bing" would not be a column otherwise, which is different from the case above. Then you might ask, why doesn't `<row>bing</row>` result in a single string column `_VALUE`? it doesn't and, maybe that would be reasonable too, but less clearly so.

One decent argument is, why doesn't spark-xml read the row element as a single struct always, anyway? It could always return a single column, struct-valued. Right now it basically always flattens that struct, but, this causes these differences in semantics. That would arguably be more consistent, but less convenient perhaps. But, that ship has sailed.

In any event it would be a schema change, which might (?) cause problems for compatibility. At version 0.x here, we make no formal guarantees about compatibility, but, still worth thinking about.

**Comment by mathiasbrem** [comment]
Hi guys,
We face exactly the same problem. In general, this occurs because there is a predefined fixed scheme or divergent schemes for a set of files that contain chained structures with empty tags or skipping lines and without using self-closed tags, example:

<row>
<foo>
</foo>
</row>

Where it could for example also come:

<row>
<foo>
<bar> </bar>
</foo>
</row>

If the scheme is defined and the tags are not being closed on the same line, such as:

<row><foo></foo> </row>

The problem occurs. To solve this, we read the data as WHOLE TEXT and apply a REGEXP to replace the spaces, later applying XML serialization using the FROM_XML function of the Databricks.

Follow:
`//READ XML LIKE A WHOLE_TEXT_FILE, REPLACE THE SPACES AND SERIALIZE THAT:

import scala.util.parsing.jasdson._
import scala.io.Source
import org.apache.spark.sql.Row asdasd
import org.apache.spark.sql.types.{ArrayType, DataType, DataTypes, DoubleType, IntegerType, MapType, StringType, StructField, StructType}
import com.databricks.spark.xml._
import spark.implicits._
import com.databricks.spark.xml.functions.from_xml
import com.databricks.spark.xml.schema_of_xml

val schemaSource = Source.fromFile(**"mySchema.json"**).getLines.mkString
val schemaFromJson = DataType.fromJson(schemaSource).asInstanceOf[StructType]

val df = spark.read.textFile(**"./myXmls/*.xml"**)

val df1 = df.toDF()
val df2 = df1.withColumn("xml", regexp_replace(col("value") , ">[\\s]*<", "><" ))
val df3 = df2.withColumn("parsed", from_xml($"xml", schemaFromJson, Map("rowTag" -> "**XXX**", "nullValue" -> "") ))
`

This is a scala example, in our case we had to implement it in Java to meet our use case.


I hope it helps other people

Mathias Brem Garcia,
Rox Partner

**Comment by srowen** [comment]
Hm, whitespace and line breaks shouldn't matter. It will parse each `<row>` with a regular XML parser. What you might be observing is that if you never have an example of `<bar>` when it infers the schema then it can't know about this one. You shouldn't have to do any of that to handle it. 

But the issue above is a bit different, concerning text elements just inside the root tag alongside other elements.

**Comment by mathiasbrem** [comment]
The serializer reads line by line and interprets those lines; if you read the entire file on one line, you can solve these problems. If this error affected you, test it out (hotfix or suggestions) and it will probably work for you.

Remembering that this applies to the case of a schema already defined through .schema ().

For dynamic schemas it may not make sense.

**Comment by srowen** [comment]
The XmlInputFormat is based on LineRecordReader, which does read a line at a time, but, it forms a single XML string per row to feed to an XML parser. If you have an issue here it's something slightly different going on.
