### ISSUE TITLE
xs:any support

### ISSUE THREAD

**Issue by trourance** [databricks/spark-xml#480]
Hi,
I was trying to create a schema from a XSD using XSDToSchema. It failed with the following error:
```
scala.MatchError: org.apache.ws.commons.schema.XmlSchemaAny@afdf919f (of class org.apache.ws.commons.schema.XmlSchemaAny)
  at com.databricks.spark.xml.util.XSDToSchema$.$anonfun$getStructField$4(XSDToSchema.scala:165)
```
I've found it's because the XSD has this complexType defined in it:
```
<xs:complexType name="SupplementaryDataEnvelope1">
    <xs:sequence>
        <xs:any namespace="##any" processContents="lax"/>
    </xs:sequence>
</xs:complexType>
```
It seems there was a proposal to support this type as string here: https://github.com/databricks/spark-xml/issues/449

Any chance to support process for this type ?

**Comment by srowen** [comment]
That issue was referring to the simple type anyType, which is something else. That's handled as a string, yes.
I don't know XSDs well but this seems to be about namespaces. It doesn't define a type? there is no name, etc - it's not an XSD element. If you want a sequence of anyType you'd write an xs:element in there.

What the parser can do is just ignore things it doesn't recognize like this, at least. I'm not sure if the result would be 'correct' in all cases because handling namespaces is tricky, but at least it wouldn't fail.

That said in your case it would still not be valid I think, as there is nothing inside the sequence?

**Comment by trourance** [comment]
I should have been more precise. This is how is defined the element that uses the complex type where xs:any is included:
```
<xs:complexType name="SupplementaryData1">
    <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="0" name="PlcAndNm" type="Max350Text"/>
        <xs:element name="Envlp" type="SupplementaryDataEnvelope1"/>
    </xs:sequence>
</xs:complexType>
<xs:complexType name="SupplementaryDataEnvelope1">
    <xs:sequence>
        <xs:any namespace="##any" processContents="lax"/>
    </xs:sequence>
</xs:complexType>
```

**Comment by srowen** [comment]
I may just not know enough, but I don't know what the second sequence is meant to be. xs:any doesn't appear to define any type.

**Comment by trourance** [comment]
It seems correct, xs:any doesn't define any type. I understand that you can put whatever you want in it.

https://www.w3schools.com/xml/el_any.asp
https://www.w3schools.com/xml/schema_complex_any.asp

**Comment by srowen** [comment]
I see, if it means something like an element or elements of any type, I agree that can be handled as a string field. It's a bit of a hack because it's not really a string, but, I don't see a cleaner interpretation when trying to force this into a tabular schema.

The problem is, there is no defined name for it. We can inject a field with name "any" or something and type "string", but when parsing XML, it won't match the real element that appears, which will be `<foo>` or something. We'd have to understand that it really is meant to match any child element that isn't otherwise matched. That seems hard to get right, not impossible, but would need a lot of change I think to special-case it.

Do you happen to know what element will appear here? you can always manually modify the XSD schema (or the parsed schema, once I make it ignore this maybe) to define that instead.

**Comment by trourance** [comment]
Unfortunately, I don't have any related xml file at the moment. I'll try to find one in order to see what's inside that element.

**Comment by trourance** [comment]
Any idea on how we may bypass this current limitation ?
At the moment, I can't generate the schema from XSD for ISO20022 (https://www.iso20022.org/iso-20022-message-definitions), because most of them use this xs:any element for SupplementaryDataEnvelope1.

**Comment by srowen** [comment]
As a workaround, can you modify the schema so that the _parent_ of the `xs:any` element is a string? that would cause the parent's content to be parsed as a string of XML, and avoids parsing the element. But that means everything under the parent is not parsed for you, not just the `xs:any`. I'm not sure if that is acceptable for your usage? You could further manually parse the XML if you had to.

**Comment by srowen** [comment]
I started working on this today and actually I don't think it's hard to implement the idea at the top. I'll see if I can get a PR today.

**Comment by srowen** [comment]
@HyukjinKwon a question for you - so I have this working but one behavior is odd. I think I understand why but it's a little surprising and maybe not desirable.

I'm creating a special schema element `xs_any` to match any XML children not otherwise in the schema. That would basically implement what `xs:any` tries to specify. So if I have XML like:

```
<row>
 <foo>...</foo>
 <bar>...</bar>
 <baz>...</baz>
</row>
```

and schema like `foo: string, xs_any: array<string>` then it is supposed to put the XML for `bar` and `baz` into the array of strings. I've got that working OK.

However if I parse that XML with that kind of schema, then `.select("xs_any")`, I find that the `xs_any` element has all three elements' values, as if `foo` was not in the schema at all even though that's how it was given.

I suppose this is something about Spark being smart and passing down just the schema that's necessary, to avoid parsing other elements that are not chosen. But of course given the behavior I'm trying to implement, it changes the result.

Is that just how it is? is it something you recall that we might need to tweak in spark-xml?
I mean, the behavior isn't out of the question for this niche use case, but it looks surprising to me.

**Comment by srowen** [comment]
I'm going to add this. It won't break existing workloads, and if the functionality works oddly in some cases mentioned above, well, it's still good to have it mostly working.
