### ISSUE TITLE
Schema difference

### ISSUE THREAD

**Issue by trourance** [databricks/spark-xml#484]
At the moment, it's not possible to generate a schema with a xsd file and read a xml file using the previously generated schema.
Result to do so will give you a runtime exception `The 0th field '...' of input row cannot be null.`
Trying to infer schema directly from xml file will also give you a different result than the one generated from xsd.
I tried the 'shiporder' example at https://www.w3schools.com/xml/schema_example.asp
Schema generated from xsd:
```
root
 |-- shiporder: struct (nullable = false)
 |    |-- orderperson: string (nullable = false)
 |    |-- shipto: struct (nullable = false)
 |    |    |-- name: string (nullable = false)
 |    |    |-- address: string (nullable = false)
 |    |    |-- city: string (nullable = false)
 |    |    |-- country: string (nullable = false)
 |    |-- item: array (nullable = false)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- title: string (nullable = false)
 |    |    |    |-- note: string (nullable = true)
 |    |    |    |-- quantity: integer (nullable = false)
 |    |    |    |-- price: decimal(38,18) (nullable = false)
 |    |-- _orderid: string (nullable = false)
```

 Schema inferred from xml using `rowTag` 'shiporder':
```
root
 |-- _orderid: long (nullable = true)
 |-- _xmlns:xsi: string (nullable = true)
 |-- _xsi:noNamespaceSchemaLocation: string (nullable = true)
 |-- item: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- note: string (nullable = true)
 |    |    |-- price: double (nullable = true)
 |    |    |-- quantity: long (nullable = true)
 |    |    |-- title: string (nullable = true)
 |-- orderperson: string (nullable = true)
 |-- shipto: struct (nullable = true)
 |    |-- address: string (nullable = true)
 |    |-- city: string (nullable = true)
 |    |-- country: string (nullable = true)
 |    |-- name: string (nullable = true)
```

**Comment by srowen** [comment]
Yes, this doesn't 100% work in many cases.

In this example though, you will need to pull out the schema of `shiporder` to use to parse, at least. That is really the structure of the row tag, not a child of it. That looks roughly 'correct' then.

What I'm not sure of is what it will do with the xmlns and xsi attributes. If they're not in the schema then it may not like parsing those, even though they are kind of metadata. If that's an issue we may have to look at special-casing some namespaces to ignore optionally.

I would in general recommend using schema inference as it can, for example, correctly infer more specific types like long for order ID.

**Comment by trourance** [comment]
I don't fully agree with your last comment, because in this example it infers `orderid` as long, which is wrong as the xsd defines it as `xs:string`.
Anyway, if I understand correctly, XSDToSchema needs to be fixed in order to generate a correct schema, otherwise the xsd file will have to be manually modified.

**Comment by srowen** [comment]
Yeah, that's what the XSD says - though may be that it's really more specifically a long in the data. Or, on the other hand, a sample of the data may make the order ID appear like it could be a long when it's not.

The XSD parser will never be 'complete' because XSDs can define schemas that do not correspond to a tabular structure. But it isn't even going to get 100% of that right.

This however looks like it is working as intended on this simple schema, modulo:
- Need to make it clear that a schema with one root element will need to be 'unpacked' one level to get the desired row tag schema - or maybe change behavior to do that by default
- Not sure it will parse the metadata attributes as they're not in the defined XSD schema

You may need to modify the parsed schema. The intended usage pattern is still pretty much to infer a schema over a representative sample, or define it manually. (You can also validate the row tag XML directly against an XSD)

**Comment by trourance** [comment]
Perfect, thanks for your support and clarification.

**Comment by srowen** [comment]
I opened a PR above that is related - rather than always assume the XSD has one root element, which the current code does, and unwrap it, I wanted to allow for multiple root elements. In which case, you can't really automatically unpack the schema for the caller as there may be multiple ones. But I documented that.

I did confirm that the parser will ignore attributes in the input that aren't in the schema, which is itself a bit of a question mark for me: should that be an error?
