### ISSUE TITLE
Text omitted for embedded tags

### ISSUE THREAD

**Issue by radislavkireev** [databricks/spark-xml#516]
Hello, 

Trying to load file : 
`<root>
	<tag1>Hello <tag2>the text</tag2> World!</tag1>
</root>`

The code is pretty straightforward: 
```
df=spark.read.format('com.databricks.spark.xml')\
  .option('mode', 'FAILFAST')\
  .option('rowTag', 'root')\
  .load('/mnt/datalake/sample.xml')

df.show()
```
The text "World!" is skipped, output:

+------+--------+
|  tag1|    tag2|
+------+--------+
|Hello |the text|
+------+--------+

May you advice any workarounds please? Not sure if the root cause is the same as in https://github.com/databricks/spark-xml/issues/428. 

Regards,
Radislav

**Comment by srowen** [comment]
Yeah, this isn't supported. Part of the issue is the semantics: what would the right type for `tag1` be? Does it have a single string member with all that text, or two, or an array?

It would be reasonably hard to support, I think, knowing how the code works -- which doesn't mean it shouldn't be. But I also wonder how common this is in the type of XML one normally feeds. That's "HTML-like" XML, whereas usually we see tags with only a value child or only tag children in XML that encodes structured data.

Not quite the same thing as #428 but similar challenges and questions.

**Comment by radislavkireev** [comment]
> Part of the issue is the semantics: what would the right type for tag1 be? 

Would it be possible to use custom schema as a hint? 

>  how common this is in the type of XML one normally feeds

Not so many. In my particular case it is about 1% of the overall, however in absolute values there are millions of files.

**Comment by srowen** [comment]
No it just doesn't parse this at the moment. You can take a look at the code and see if there is actually a clean way to handle this case.

**Comment by nkarpovdb** [comment]
It's already been noted that this isn't supported. I just want to note that this isn't isolated to the element with embedded tags. There can be other fatal side effects, for example:
```
<Parent>
  <Child1>Child1</Child1>
  <Child2>
    <ElementWithEmbeddedTags>
      BeforeText
      <SomeTag/>
    </ElementWithEmbeddedTags>
  </Child2>
  <Child3>Child3</Child3>
</Parent>
```
In this case, when `ElementWithEmbeddedTags` is the child of top level `Child2`, doing a `df.select` on any further element, like `Child3` will produce `null`. This isn't the case if `ElementWithEmbeddedTags` is itself a "top level" element. This is assuming `<Parent>` is your `rowTag`.

**Comment by srowen** [comment]
No, it just doesn't do this. This is 'unusual' for the type of XML that is typically used to encode tabular-like data. The semantics are not clear. It's not crazy or impossible to do, just hard to do, so don't think it's going to happen unless someone comes up with a clean solution
