### ISSUE TITLE
Setting Timestamp Format as an Option

### ISSUE THREAD

**Issue by ma-khalil** [databricks/spark-xml#519]
Hi,

Is there a way to set the timestamp format as an option, like we do in reading the `csv` files, the `timestampFormat` option?

I've tried setting it using the following code

```
spark.read
      .option("rowTag", "row")
      .option("timestampFormat", "dd-MM-yyyy")
      .schema(schema)
      .xml("test.xml").show()
```
But it always returns null in the `Timestamp` field. Also, I've tried searching for a method representing that option in the `XMLReader` but I couldn't find any.

It would be really great if you could add setting the `timestamp` as an option while reading the XML files, if it's not already there :)

**Comment by srowen** [comment]
Can you show your schema and sample XML? There is some support for parsing dates, but I am not sure if it's 100% right. Timestamps (with hour/minute/second) should work.

**Comment by ma-khalil** [comment]
> Timestamps (with hour/minute/second) should work.

I've tried adding hour/minute/second with the format proposed above, but it didn't work. Only the default one, with hour/minute/second written, works. Probably, the data that I'd get won't contain hours/minutes/seconds in it.

Here's the XML:

```
<book>
    <author>John Smith</author>
    <date>01-01-2021</date>
</book>
```

Here's the schema as well:

```
root
 |-- author: string (nullable = true)
 |-- date: timestamp (nullable = true)
```

Here's the complete code reading the XML:
```
import com.databricks.spark.xml._
import org.apache.spark.sql.SparkSession
import org.apache.log4j.{Level, Logger}
import org.apache.spark.sql.types.{StringType, StructField, StructType, TimestampType}

object Main {
  def main(args: Array[String]): Unit = {
    Logger.getLogger("org").setLevel(Level.ERROR)
    val spark = SparkSession
      .builder()
      .master("local")
      .getOrCreate()

    val schema = StructType(
      Array(
        StructField("author", StringType),
        StructField("date", TimestampType)
      )
    )

    schema.printTreeString()

    spark.read
      .option("rowTag", "book")
      .option("timestampFormat", "dd-MM-yyyy")
      .schema(schema)
      .xml("test.xml").show()
  }
}
```

**Comment by srowen** [comment]
A few things are going on here -

You'll need to specify `DateType` in the schema as this isn't a timestamp.
I also found that schema inference doesn't correctly infer date, and can fix that, but it isn't your issue here.
It works if you use ISO formatted dates like "2021-01-01". 

I assume you have to override that right, because your data isn't ISO formatted? 
There isn't a timestampFormat or dateFormat option now. But, seems like that is the feature request then.

I guess the semantics would be, if you specify the format for date or time, that it will only accept that format and not ISO-formatted ones? or merely add to the list of formats it will accept?
