### ISSUE TITLE
Line breaks affect parsing

### ISSUE THREAD

**Issue by nkarpovdb** [databricks/spark-xml#541]
Have the following two structurally equivalent XML snippets that behave differently:

`broken.xml`
```
<T1>
  <T2>
    <attach>
        <_>24</_>
        <_>30</_>
    </attach>
  </T2>
</T1>
```

`fixed.xml`
```
<T1>
  <T2>
    <attach><_>24</_><_>30</_></attach>
  </T2>
</T1>
```

The only difference in `fixed.xml` is that nested `<_>` appear on the same line as the parent - and it successfully parses. When the nested `<_>` elements appear on newlines they are not parsed at all. Setting `attributePrefix` to something other than `_` does "fix" things but in any case I don't *think* line breaks should have this impact(?).

This is with Spark 3 (DBR 8.2) with the latest maven hosted spark-xml `com.databricks:spark-xml_2.12:0.12.0`

Here is a Databricks based scala notebook for easy repro

```
// Databricks notebook source
// MAGIC %sh
// MAGIC echo '<T1>
// MAGIC   <T2>
// MAGIC     <attach>
// MAGIC       <_>24</_>
// MAGIC       <_>30</_>
// MAGIC     </attach>
// MAGIC   </T2>
// MAGIC </T1>' > /dbfs/broken.xml

// COMMAND ----------

val df = spark.read.format("xml").option("rowTag","T2").load("dbfs:/broken.xml")
display(df)

// COMMAND ----------

// MAGIC %sh
// MAGIC echo '<T1>
// MAGIC   <T2>
// MAGIC     <attach><_>24</_><_>30</_></attach>
// MAGIC   </T2>
// MAGIC </T1>' > /dbfs/fixed.xml

// COMMAND ----------

val df = spark.read.format("xml").option("rowTag","T2").load("dbfs:/fixed.xml")
display(df)

```

**Comment by srowen** [comment]
Yeah it's something to do with `_` being used as the attribute prefix - I would definitely set that otherwise if you don't want it to be interpreted as an attribute. Line breaks shouldn't matter.

... but after debugging this for about 20 minutes, I can see the problem, just not a super easy fix. It handles the case where a struct has character data vs no character data differently, because it's looking for a `_VALUE` tag. That is at least the immediate reason the code paths are not the same. And then in that case, it believes every schema element is an attribute as they start with `_`.

I think it's... really hard to fix without thinking about it for a long time - just a complex set of cases being handled here and old creaky code in this section.

One option is to always interpret a field that is _only_ the attributePrefix as a field, not attribute. I'm not sure that quite fixes this case but maybe. Or disallow this situation earlier on entirely. Or just indeed set `attributePrefix` differently or avoid these field names.
