### ISSUE TITLE
Corrupted records do not show in filter on _corrupt_record column when counted

### ISSUE THREAD

**Issue by ajavanmardi** [databricks/spark-xml#548]
We created an xml file with a corrupted record. The price column for the corrupted record is not DoubleType(), but is StringType().
[corrupted books.txt](https://github.com/databricks/spark-xml/files/6737017/corrupted.books.txt)
Then we used the code below to load the xml records into a dataframe in pyspark:

```
schema = StructType([
  StructField('_id', StringType(), True),
  StructField('author', StringType(), True),
  StructField('description', StringType(), True), 
  StructField('genre', StringType(), True),
  StructField('price', DoubleType(), True),
  StructField('publish_date', DateType(), True),
  StructField('title', StringType(), True)
]) 

corrupted_column_name = '_corrupt_record'
corrupted_column = StructField(corrupted_column_name, StringType(), True)
schema = schema.add(corrupted_column)

file_location = '/FileStore/shared_uploads/ar.javanmardi@sdktek.com/books_corrupted.xml'

df = (spark.read.format('xml')
      .option('rootTag', 'books')
      .option('rowTag', 'book')
      .option('mode', 'PERMISSIVE')
      .option('columnNameOfCorruptRecord', corrupted_column_name)
      .load(file_location, schema = schema))
```

The XML file has 12 records and one of them is corrupted, so if I filter "_corrupt_record" column to only capture non-null values and count the number of records in the dataframe, I should get 1 record. However, the output of the code snippet below is "0".

`df.filter(f.col('_corrupt_record').isNotNull()).count()`

![image](https://user-images.githubusercontent.com/83658478/123880067-1ecddc80-d8ff-11eb-9379-83b3384e0e67.png)

Meanwhile if I display the output of the above query, I get the corrupted record displayed:

`display(df.where(f.col('_corrupt_record').isNotNull()))`

![image](https://user-images.githubusercontent.com/83658478/123880186-5e94c400-d8ff-11eb-99b3-f941bc6192f2.png)

On the other hand if I cache the dataframe before counting the number of corrupted records, I get the right result:

```
df.cache()
df.filter(f.col('_corrupt_record').isNotNull()).count()
```

![image](https://user-images.githubusercontent.com/83658478/123880273-884deb00-d8ff-11eb-8d3c-d5fe33e2694c.png)

**Comment by srowen** [comment]
This is a bug I've seen before, and it's weird, and I don't know how to fix it.

The issue is that when you _only_ filter for `_corrupt_record`, the projection kindly tells spark-xml to not bother looking for any other columns. Having not parsed anything else, it finds nothing corrupt. However if you actually parse for everything, it finds the corrupt column correctly and reports it. 

The only workaround I know is to parse everything to be sure, persist it, then try.

Of course I suppose somehow it's possible to special case this - if you select for the columnNameOfCorruptRecord at all, then really every column has to be parsed. I just never looked into it enough to understand how to do that without messing a lot with the otherwise nice implementation detail that it'll skip parsing anything you don't ask for.
