### ISSUE TITLE
Should test against Hadoop 1.x and Hadoop 2.x in Travis

### ISSUE THREAD

**Issue by rxin** [databricks/spark-xml#6]
This library's tests should be run against both Hadoop 1.x and 2.x in Jenkins, since binary incompatibilities in Hadoop's TaskAttemptContext class may mean that your published artifact may not be compatible with both versions. See https://github.com/databricks/spark-avro/pull/79 for an example of a similar PR against spark-avro and https://github.com/harsha2010/magellan/pull/25 for a PR against magellan, another Spark package.

I think this is especially important for this library, given that it includes a Hadoop InputFormat.

Link from https://github.com/HyukjinKwon/spark-xml/issues/5

**Comment by HyukjinKwon** [comment]
@JoshRosen I changed (locally) the `TextInputFormat` from Hadoop 2.x (`org.apache.hadoop.mapreduce`) to 1.x (`org.apache.hadoop.mapred`) and I checked the codes run okay on Hadoop 2.x.

As it looks Hadoop supports full binary compatibility (according to [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/Compatibility.html) and [here](http://hortonworks.com/blog/running-existing-applications-on-hadoop-2-yarn)), I think I better use old APIs for this and then does not add separate tests for that. (I am somehow a bit worried though). 

Do you think this would be okay and safe?

**Comment by JoshRosen** [comment]
Independently of how we change the actual code, it's important that our automated tests run all of our tests against both Hadoop 1.x and 2.x, since we also need to guard against future changes which might introduce incompatibilities. We don't necessarily need _dedicated_ tests for Hadoop compatibility, though; just running the existing tests with Hadoop versions configured in the builds (like I did in the issues linked above) should probably be sufficient for now.

**Comment by HyukjinKwon** [comment]
I see. Thanks!

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/databricks/spark-xml/pull/14
